//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (1.4.0)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Users Table
class UsersTable extends SupabaseTable<UsersRow> {
  /// Table Name
  @override
  String get tableName => 'users';

  /// Create a [UsersRow] from the [data] provided
  @override
  UsersRow createRow(Map<String, dynamic> data) => UsersRow.fromJson(data);
}

/// Users Row
class UsersRow extends SupabaseDataRow {
  /// Users Row
  UsersRow({
    required String id,
    required String username,
    String? profileImage,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) : super({
         'id': supaSerialize(id),
         'username': supaSerialize(username),
         if (profileImage != null) 'profile_image': supaSerialize(profileImage),
         if (createdAt != null) 'created_at': supaSerialize(createdAt),
         if (updatedAt != null) 'updated_at': supaSerialize(updatedAt),
       });

  /// Users Row
  const UsersRow._(super.data);

  /// Create Users Row from a [data] map
  factory UsersRow.fromJson(Map<String, dynamic> data) =>
      UsersRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => UsersTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  String get id => getField<String>(idField)!;
  set id(String value) => setField<String>(idField, value);

  /// Username field name
  static const String usernameField = 'username';

  /// Username
  String get username => getField<String>(usernameField)!;
  set username(String value) => setField<String>(usernameField, value);

  /// Profile Image field name
  static const String profileImageField = 'profile_image';

  /// Profile Image
  String? get profileImage => getField<String>(profileImageField);
  set profileImage(String? value) => setField<String>(profileImageField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Updated At field name
  static const String updatedAtField = 'updated_at';

  /// Updated At
  DateTime get updatedAt =>
      getField<DateTime>(updatedAtField, defaultValue: DateTime.now())!;
  set updatedAt(DateTime value) => setField<DateTime>(updatedAtField, value);

  /// Make a copy of the current [UsersRow]
  /// overriding the provided fields
  UsersRow copyWith({
    String? id,
    String? username,
    String? profileImage,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) => UsersRow.fromJson({
    'id': supaSerialize(id) ?? data['id'],
    'username': supaSerialize(username) ?? data['username'],
    'profile_image': supaSerialize(profileImage) ?? data['profile_image'],
    'created_at': supaSerialize(createdAt) ?? data['created_at'],
    'updated_at': supaSerialize(updatedAt) ?? data['updated_at'],
  });
}

/// Date: 2025-08-19 19:50:02.608368
