name: sns
description: "sns project"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  freezed: ^3.0.4
  freezed_annotation: ^3.0.0
  either_dart: ^1.0.0
  envied: ^1.1.1
  flutter_bloc: ^9.1.0
  go_router: ^14.8.1
  get_it: ^8.0.3
  injectable: ^2.5.0
  logger: ^2.5.0
  copy_with_extension: ^6.0.1
  supabase_flutter: ^2.9.1
  bloc_test: ^10.0.0
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  injectable_generator: ^2.6.2
  envied_generator: ^1.1.1
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
