enum ErrorCode {
  invalidCredential,
  ratedLimited,
  invalidParam,
  notFound,
  duplicated,
  permissionDenied,
  conflict,
  internalServer,
  network,
  unAuthorized,
  tooLargeRequest,
  unSupportedMedia,
  unKnown,
}
