//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (2.0.0)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

export 'enums/_enums.dart';
export 'tables/_tables.dart';

/// Tag: v1
