name: supabase_datasource
description: supabase auth, database, storage
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.0
  flutter: ^3.32.0

dependencies:
  flutter:
    sdk: flutter
  response_wrapper:
    path: ../response_wrapper
  env:
    path: ../env

  freezed: ^3.0.4
  freezed_annotation: ^3.0.0
  logger: ^2.5.0
  supabase_flutter: ^2.9.1
  supabase_codegen: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  injectable_generator: ^2.6.2
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  copy_with_extension_gen: ^6.0.1
